# Lecture 2 : Operations

### setup

In [1]:
import os, sys
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
%matplotlib inline

print(tf.__version__)
sess_config = tf.ConfigProto(gpu_options=tf.GPUOptions(allow_growth=True))

1.2.0


## 1. Fun with Tensorboard

In [2]:
# Nodes: operators, variables, and constants 
# Edges: tensors

a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a,b)
print(a, b, x)
with tf.Session(config = sess_config) as sess:
    print(sess.run(x))

Tensor("Const:0", shape=(), dtype=int32) Tensor("Const_1:0", shape=(), dtype=int32) Tensor("Add:0", shape=(), dtype=int32)
5


In [3]:
# to visualizer above program with Tensorboard

tf.reset_default_graph()

a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a,b)

# Create the summary writer after graph definition and before running your
# session
writer = tf.summary.FileWriter(logdir = '../graphs/lecture02/add_example',
                      graph = tf.get_default_graph())
writer.close()
with tf.Session(config = sess_config) as sess:
    print(sess.run(x))

5


#### 텐서보드 실행법

로그파일을 실행 후, 터미널을 켜서 아래의 코드를 실행


```$ python [my_program.py]
$ tensorboard --logdir="logdir" --port 6006 ```

## 2. Constant op

In [4]:
# constant of 1-d tensor (vector type)

a = tf.constant([2,2], name = 'vector')
print(a)
with tf.Session(config = sess_config) as sess:
    print(sess.run(a))

Tensor("vector:0", shape=(2,), dtype=int32)
[2 2]


In [5]:
# constant of 2x2 tensor (matrix type)

b = tf.constant([[0,1], [2,3]], name = 'matrix')
print(b)

with tf.Session(config = sess_config) as sess:
    print(sess.run(b))

Tensor("matrix:0", shape=(2, 2), dtype=int32)
[[0 1]
 [2 3]]


In [6]:
# create a tensor of shape and all elements are zeros -> tf.zeros

print(tf.zeros(shape = [2,3], dtype = tf.int32))
with tf.Session(config = sess_config) as sess:
    print(sess.run(tf.zeros(shape = [2,3], dtype = tf.int32)))

Tensor("zeros:0", shape=(2, 3), dtype=int32)
[[0 0 0]
 [0 0 0]]


In [7]:
# create a tensor of shape and type as the input_tensor but all elements are zore.

input_tensor = [[0,1], [2,3], [4,5]]
print(tf.zeros_like(input_tensor))
with tf.Session(config = sess_config) as sess:
    print(sess.run(tf.zeros_like(input_tensor)))

Tensor("zeros_like:0", shape=(3, 2), dtype=int32)
[[0 0]
 [0 0]
 [0 0]]


크기를 튜플로 명시하지 않고, 다른 배열과 같은 크기의 배열을 생성하고 싶을 때 zeros_like를 사용

In [8]:
# create a tensor of shape and all elements are ones
print(tf.ones(shape = [2,3], dtype = tf.int32))
with tf.Session(config = sess_config) as sess:
    print(sess.run(tf.ones(shape = [2,3], dtype = tf.int32)))

Tensor("ones:0", shape=(2, 3), dtype=int32)
[[1 1 1]
 [1 1 1]]


In [9]:
# create a tensor of shape and type (unless type is specified) as the input_tensor but all elements are ones.

print(tf.ones_like(input_tensor))
with tf.Session(config = sess_config) as sess:
    print(sess.run(tf.ones_like(input_tensor)))

Tensor("ones_like:0", shape=(3, 2), dtype=int32)
[[1 1]
 [1 1]
 [1 1]]


In [10]:
# create a tensor filled with a scalar value.

print(tf.fill([2,3],8))
with tf.Session(config = sess_config) as sess:
    print(sess.run(tf.fill([2,3], 8)))

Tensor("Fill:0", shape=(2, 3), dtype=int32)
[[8 8 8]
 [8 8 8]]


In [11]:
'''
create a sequence of num evenly-spaced values are generated beginning at start. If num >
1, the values in the sequence increase by (stop - start) / (num - 1), so that the last one
is exactly stop. comparable to but slightly different from numpy.linspace
'''

print(tf.lin_space(10., 13., 4))
with tf.Session(config = sess_config) as sess:
    print(sess.run(tf.lin_space(10., 13., 4)))

Tensor("LinSpace:0", shape=(4,), dtype=float32)
[10. 11. 12. 13.]


numpy.linspace : 선형 구간을 지정한 수 만큼 분할한다.

In [12]:
# create a sequence of numbers that begins at start and extends 
# by increments of delta up to
# but not including limit
print(tf.range(5)) 
with tf.Session(config = sess_config) as sess:
    print(sess.run(tf.range(5)))
    
    # TensorFlow sequences are not iterable

Tensor("range:0", shape=(5,), dtype=int32)
[0 1 2 3 4]


In [13]:
with tf.Session(config = sess_config) as sess:
    print(sess.run(tf.range(3, 18, 3)))
    print(sess.run(tf.range(3, 1, -.5)))
    print(sess.run(tf.range(5)))

[ 3  6  9 12 15]
[3.  2.5 2.  1.5]
[0 1 2 3 4]


tf.range(3, 18, 3) -> (시작, 끝(미포함), 단위)

In [14]:
for _ in tf.range(4):
    print(_)

TypeError: 'Tensor' object is not iterable.

그 외에도

```tf.random_normal
tf.truncated_normal
tf.random_uniform
tf.random_shuffle
tf.random_crop
tf.multinomial
tf.random_gamma
tf.set_random_seed```

가 존재한다. 

[함수 링크]("https://www.tensorflow.org/api_guides/python/constant_op")

### Pass Math operation, data type

[참고][Math operation]("https://www.tensorflow.org/api_docs/python/tf/math/divide")

[참고] data type


```tf.float16: 16-bit half-precision floating-point.
tf.float32: 32-bit single-precision floating-point.
tf.float64: 64-bit double-precision floating-point.
tf.bfloat16: 16-bit truncated floating-point.
tf.complex64: 64-bit single-precision complex.
tf.complex128: 128-bit double-precision complex.
tf.int8: 8-bit signed integer.
tf.uint8: 8-bit unsigned integer.
tf.uint16: 16-bit unsigned integer.
tf.uint32: 32-bit unsigned integer.
tf.uint64: 64-bit unsigned integer.
tf.int16: 16-bit signed integer.
tf.int32: 32-bit signed integer.
tf.int64: 64-bit signed integer.
tf.bool: Boolean.
tf.string: String.
tf.qint8: Quantized 8-bit signed integer.
tf.quint8: Quantized 8-bit unsigned integer.
tf.qint16: Quantized 16-bit signed integer.
tf.quint16: Quantized 16-bit unsigned integer.
tf.qint32: Quantized 32-bit signed integer.
tf.resource: Handle to a mutable resource.
tf.variant: Values of arbitrary types.```

## 5. Variables

In [15]:
tf.reset_default_graph()

In [16]:
# Create variables
# Note that when we use tf.constant as an initializer,
# we don't need to provide shape

s = tf.get_variable(name = 'scalar',
                    initializer = tf.constant(2))
m = tf.get_variable(name = 'matrix',
                    initializer = tf.constant([[0, 1], [2, 3]]))
W = tf.get_variable(name = 'big_matrix', shape = [784, 10],
                    initializer = tf.zeros_initializer())

In [17]:
# Initialize variables
with tf.Session(config = sess_config) as sess:
    print(sess.run(tf.report_uninitialized_variables()))

[b'scalar' b'matrix' b'big_matrix']


In [18]:
with tf.Session(config = sess_config) as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(tf.report_uninitialized_variables()))

[]


변수 초기화 작업

In [19]:
# Interesting Assign example

tf.reset_default_graph()
W = tf.Variable(10)
W.assign(100)

with tf.Session(config = sess_config) as sess:
    sess.run(W.initializer)
    print(W.eval())

10


In [20]:
tf.reset_default_graph()
W = tf.Variable(10)
assign_op = W.assign(100)

with tf.Session(config = sess_config) as sess:
    sess.run(assign_op)
    print(W.eval())

100


잘 몰라서 텐서플로우 코리아 코드

```
# 값이 0인 스칼라로 초기화된 변수를 만듭니다.
# Create a Variable, that will be initialized to the scalar value 0.
state = tf.Variable(0, name="counter")

# 'state'에 1을 더하는 작업(op)을 만듭니다.
# Create an Op to add one to `state`.

one = tf.constant(1)
new_value = tf.add(state, one)
update = tf.assign(state, new_value)

# 그래프를 한 번 작동시킨 후에는 'init' 작업(op)을 실행해서 변수를 초기화해야
# 합니다. 먼저 'init' 작업(op)을 추가해 봅시다.
# Variables must be initialized by running an `init` Op after having
# launched the graph.  We first have to add the `init` Op to the graph.
init_op = tf.global_variables_initializer()

# graph와 작업(op)들을 실행시킵니다.
# Launch the graph and run the ops.
with tf.Session() as sess:
  # 'init' 작업(op)을 실행합니다.
  # Run the 'init' op
  sess.run(init_op)
  # 'state'의 시작값을 출력합니다.
  # Print the initial value of 'state'
  print(sess.run(state))
  # 'state'값을 업데이트하고 출력하는 작업(op)을 실행합니다.
  # Run the op that updates 'state' and print 'state'.
  for _ in range(3):
    sess.run(update)
    print(sess.run(state))

# output:

# 0
# 1
# 2
# 3
```

In [23]:
tf.reset_default_graph()
W = tf.get_variable(name = 'weights', initializer = tf.constant([[1.,1.],[2.,2.]]))
tf.get_variable_scope().reuse_variables()
w = tf.get_variable(name = 'weights')
writer = tf.summary.FileWriter(logdir = '../graphs/lecture02/get_variables',
                      graph = tf.get_default_graph())
writer.close()

with tf.Session(config = sess_config) as sess:
    sess.run(tf.global_variables_initializer())
    print(W, sess.run(W))
    print(w, sess.run(w))

<tf.Variable 'weights:0' shape=(2, 2) dtype=float32_ref> [[1. 1.]
 [2. 2.]]
<tf.Variable 'weights:0' shape=(2, 2) dtype=float32_ref> [[1. 1.]
 [2. 2.]]


## 6. Interactive Session

## 7. Control Dependencies

## 8. Importing Data

In [24]:
tf.reset_default_graph()
a = tf.placeholder(dtype = tf.float32, shape = [3])
b = tf.constant(value = [5, 5, 5], dtype = tf.float32)
c = a + b

writer = tf.summary.FileWriter(logdir = '../graphs/lecture02/placeholder',
                               graph = tf.get_default_graph())

with tf.Session(config = sess_config) as sess:
    print(sess.run(c, feed_dict = {a : [1.,2.,3.]}))

[6. 7. 8.]


In [25]:
tf.reset_default_graph()
a = tf.add(2, 5)
b = tf.multiply(a, 3)

with tf.Session(config = sess_config) as sess:
    print(sess.run(b))
    print(sess.run(b, feed_dict={a : 15}))

21
45


In [26]:
with tf.Session(config = sess_config) as sess:
    print(sess.graph.is_feedable(a), sess.graph.is_feedable(b))

True True


## 9. The trap of lazy loading

lazying loading : 지연 로딩(?). 컴퓨터 디자인 패턴중의 하나

실제로 접근할 때만 초기화해서 불러오게 하는 것

In [28]:
1# normal loading
tf.reset_default_graph()
x = tf.get_variable(name = 'x', initializer = tf.constant(10))
y = tf.get_variable(name = 'y', initializer = tf.constant(20))
z = tf.add(x,y)

with tf.Session(config = sess_config) as sess:
    sess.run(tf.global_variables_initializer())
    writer = tf.summary.FileWriter(logdir = '../graphs/lecture02/normal_loading',
                                   graph = tf.get_default_graph())
    
    for _ in range(3):
        sess.run(z)
    else:
        print(tf.get_default_graph().as_graph_def())
        writer.close()

node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 10
      }
    }
  }
}
node {
  name: "x"
  op: "VariableV2"
  attr {
    key: "container"
    value {
      s: ""
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
      }
    }
  }
  attr {
    key: "shared_name"
    value {
      s: ""
    }
  }
}
node {
  name: "x/Assign"
  op: "Assign"
  input: "x"
  input: "Const"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@x"
      }
    }
  }
  attr {
    key: "use_locking"
    value {
      b: true
    }
  }
  attr {
    key: "validate_shape"
    value {
      b: true
    }
  }
}
node {
  name: "x/read"
  op: "Identity"
  input: "x"
  attr {
    k

In [29]:
# lazy loading
tf.reset_default_graph()
x = tf.get_variable(name = 'x', initializer = tf.constant(10))
y = tf.get_variable(name = 'y', initializer = tf.constant(20))

with tf.Session(config = sess_config) as sess:
    sess.run(tf.global_variables_initializer())
    writer = tf.summary.FileWriter(logdir = '../graphs/lecture02/lazy_loading',
                                   graph = sess.graph)
    for _ in range(3):
        sess.run(tf.add(x,y))
    else:
        print(tf.get_default_graph().as_graph_def())
        writer.close()
        

node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 10
      }
    }
  }
}
node {
  name: "x"
  op: "VariableV2"
  attr {
    key: "container"
    value {
      s: ""
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
      }
    }
  }
  attr {
    key: "shared_name"
    value {
      s: ""
    }
  }
}
node {
  name: "x/Assign"
  op: "Assign"
  input: "x"
  input: "Const"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@x"
      }
    }
  }
  attr {
    key: "use_locking"
    value {
      b: true
    }
  }
  attr {
    key: "validate_shape"
    value {
      b: true
    }
  }
}
node {
  name: "x/read"
  op: "Identity"
  input: "x"
  attr {
    k