In [2]:
import numpy as np

In [3]:
x1 = np.array([[5.1],[3.5],[1.4],[0.2]])
x1

array([[ 5.1],
       [ 3.5],
       [ 1.4],
       [ 0.2]])

In [4]:
x2 = np.array([[4.9],[3.0],[1.4],[0.2]])
x2

array([[ 4.9],
       [ 3. ],
       [ 1.4],
       [ 0.2]])

In [9]:
X = np.array([[5.1,3.5,1.4,0.2],[4.9,3.0,1.4,0.2]])
X

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2]])

In [12]:
# transpose matrix
A=X.T
B=A.T
B

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2]])

In [13]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [14]:
np.identity(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [17]:
C = np.array([[0,0,0,0,0,0]])
C

array([[0, 0, 0, 0, 0, 0]])