In [1]:
import numpy as np

In [5]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

SyntaxError: invalid syntax (<ipython-input-5-135078cc5f3c>, line 1)

In [7]:
b = [0,1,2,3,4,5,6,7,8,9]

In [12]:
b = []
for ai in a:
    b.append(ai * 2)
b

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [14]:
x = np.array(a)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
x = np.array([1,2,3])
y = np.array([10,20,30])

2 * x + y

array([12, 24, 36])

In [19]:
print np.exp(x)
print np.log(y)
print np.sin(x)

[  2.71828183   7.3890561   20.08553692]
[ 2.30258509  2.99573227  3.40119738]
[ 0.84147098  0.90929743  0.14112001]


In [21]:
# 2-dimensional Array

b = np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
len(b) # 행

2

In [23]:
len(b[0]) # 열

3

In [24]:
x = np.array([[10,20,30,40],[50,60,70,80]])
x

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [26]:
# 3-dimensional Array
c = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[11,12,13,14],[15,16,17,18],[19,20,21,22]]])
# Above of this : 2 x 3 x 4 matrix

c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [27]:
print len(c)
print len(c[0])
print len(c[0][0])

2
3
4


# 배열의 차원과 크기 알아내기
배열의 차원 및 크기는 ndim 속성과 shape 속성으로 알 수 있다.

In [32]:
print c.ndim
print c.shape

3
(2L, 3L, 4L)


# 배열의 인덱싱
배열 객체로 구현한 다차원 배열의 원소 하나하나는 다음과 같이 콤마를 사용하여 접근할 수 있다.
콤마로 구분된 차원을 축 이라고도 한다. x축과 y축을 

In [33]:
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [35]:
print a[0,0]
print a[0,1]
print a[-1,-1]

0
1
5


# 배열 슬라이싱

In [3]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [11]:
a[0,:]
a[:,1]
a[1,1:]
a[:2, :2]

array([[0, 1],
       [4, 5]])

In [13]:
# 연습문제
m = np.array([[ 0,  1,  2,  3,  4],
           [ 5,  6,  7,  8,  9],
           [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
m[1,2]
m[2,4]

14

In [27]:
m[1,1:3]
m[1:,2]
m[:2,3:]

array([[3, 4],
       [8, 9]])

# 배열 인덱싱
팬시 인덱싱

In [28]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [30]:
a[a%2==0]

array([0, 2, 4, 6, 8])

In [31]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) * 10
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([ 0, 20, 40, 60, 80])

In [32]:
a = np.array([0, 1, 2, 3]) * 10
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]

array([ 0,  0,  0,  0,  0,  0, 10, 10, 10, 10, 10, 20, 20, 20, 20, 20])

- boolean (True / False)
- 위치 지정 방식