In [1]:
import numpy as np

In [2]:
x = np.arange(1,1001)
y = np.arange(1001,2001)

# 반복문

In [4]:
%%time
z = np.zeros_like(x)
for i in range(1000):
    z[i] = x[i]+y[i]

Wall time: 1e+03 µs


In [5]:
z[:10]

array([1002, 1004, 1006, 1008, 1010, 1012, 1014, 1016, 1018, 1020])

In [6]:
%%time
z = x+y

Wall time: 0 ns


In [7]:
z [:10]

array([1002, 1004, 1006, 1008, 1010, 1012, 1014, 1016, 1018, 1020])

In [19]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
c = np.array([1,2,3,4])

In [18]:
a==b

array([False,  True, False,  True], dtype=bool)

In [17]:
a >= b

array([False,  True,  True,  True], dtype=bool)

In [20]:
np.all(a==c)

True

In [23]:
a = np.arange(5)
print np.exp(a)
print 10**a
print np.log(a)
print np.log10(a)

[  1.           2.71828183   7.3890561   20.08553692  54.59815003]
[    1    10   100  1000 10000]
[       -inf  0.          0.69314718  1.09861229  1.38629436]
[       -inf  0.          0.30103     0.47712125  0.60205999]


C:\Users\Yeoni\Anaconda2\lib\site-packages\ipykernel\__main__.py:4: RuntimeWarning: divide by zero encountered in log
C:\Users\Yeoni\Anaconda2\lib\site-packages\ipykernel\__main__.py:5: RuntimeWarning: divide by zero encountered in log10


연습 문제

In [32]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 스칼라와 벡터/행렬의 곱셈

In [33]:
100*x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [36]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
100*x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

# 브로드캐스팅
- 서로 다른 두 배열의 사칙연산도 지원

In [39]:
x = np.arange(5)
y = np.ones_like(x)

print x+y
print x+1

[1 2 3 4 5]
[1 2 3 4 5]


In [47]:
a = np.tile(np.arange(0,40,10),(3,1)).T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [49]:
a = np.arange(0,40,10)[:,np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [46]:
b = np.array([0,1,2])
b

array([0, 1, 2])

In [48]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [50]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

# 차원 축소 연산
최대/최소, 통계, 불리언

In [51]:
x = np.array([1,2,3,4])

In [52]:
print np.sum(x)
print x.sum()

10
10


In [53]:
y = np.array([1,3,2])

In [55]:
print y.min()
print y.max()
print y.argmin()
print y.argmax()

1
3
0
1


In [56]:
z = np.array([1,2,3,1])

In [59]:
print z.mean()
print np.median(x)
print np.all([True,True,False])
print np.any([True,True,False])

1.75
2.5
False
True


In [61]:
a = np.zeros((100,100),dtype=np.int)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [62]:
print np.any(a!=0)
print np.all(a==a)

False
True


In [65]:
# 연산
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])

((a <= b) & (b <= c)).all()

True

- axis = 0 (열) axis = 1(행)

In [66]:
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [71]:
print x.sum()
print x.sum(axis=0)
print x.sum(axis=1)

6
[3 3]
[2 4]


- 연습 문제

In [98]:
# 5 * 6의 데이터 행렬
# 1. 전체의 최댓값

q = np.array([[1,2,3,4,5,8],[3,4,2,1,2,7],[1,0,3,9,8,10],[2,3,4,1,2,5],[1,2,3,4,5,6]])
q

print np.max(q)

# 2. 각 행의 합
print q.sum(axis=1)

# 3. 각 열의 평균
print q.mean(axis=0)

10
[23 19 31 17 21]
[ 1.6  2.2  3.   3.8  4.4  7.2]


# 정렬
- sort (원소의 크기에 따라)
- axis (2차원 이상, 방향 결정)

In [78]:
a = np.array([[4,3,5],[1,2,1]])
print np.sort(a)

[[3 4 5]
 [1 1 2]]


In [82]:
print np.sort(a,axis=1)

[[3 4 5]
 [1 1 2]]


In [83]:
print a.sort(axis=0)
a

None


array([[1, 1, 2],
       [3, 4, 5]])

In [ ]:
new = np.array([4,3,1,2])
j = np.argsort(new) # 순서만 알고 싶을때
j

- 연습 문제

In [97]:
# 연습문제 2에서의 데이터로
# 1. 첫번째 열 값으로 모든 행을 정렬

print np.sort(q, axis=0)

[[ 1  0  2  1  2  5]
 [ 1  2  3  1  2  6]
 [ 1  2  3  4  5  7]
 [ 2  3  3  4  5  8]
 [ 3  4  4  9  8 10]]


In [101]:
# 2. 두번째 행 값으로 모든 열을 정렬
print np.sort(q, axis=1)

[[ 1  2  3  4  5  8]
 [ 1  2  2  3  4  7]
 [ 0  1  3  8  9 10]
 [ 1  2  2  3  4  5]
 [ 1  2  3  4  5  6]]
