In [1]:
from sklearn import linear_model
from sklearn.neural_network import MLPClassifier

import numpy as np

## 로지스틱 회귀를 이용한 AND OR XOR

In [23]:
df_and = np.loadtxt("and.txt")

In [24]:
df_and

array([[ 0.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  1.,  1.]])

In [26]:
## AND

x_data = df_and[:,:-1]
y_data = df_and[:,-1]

logreg = linear_model.LogisticRegression(C=1e5)
logreg.fit(x_data, y_data)

prediction = logreg.predict(x_data)

print(prediction)

[ 0.  0.  0.  1.]


In [ ]:
## OR

df_or = np.loadtxt("or.txt")

x_data = df_or[:,:-1]
y_data = df_or[:,-1]

logreg = linear_model.LogisticRegression(C=1e5)
logreg.fit(x_data, y_data)

prediction = logreg.predict(x_data)

print(prediction)

In [32]:
## XOR

df_xor = np.loadtxt("xor.txt")

x_data = df_xor[:,:-1]
y_data = df_xor[:,-1]

logreg = linear_model.LogisticRegression(C=1e5)
logreg.fit(x_data, y_data)

prediction = logreg.predict(x_data)

print(prediction)

[ 0.  0.  0.  0.]


Logistic Regression으로는 XOR 불가능(한 선으로 그을 수 없음)

## scikit-learn을 이용한 NN 사용 .
## MLP : multi layer perceptron

In [35]:
mlp = MLPClassifier(hidden_layer_sizes=(4), solver='sgd', learning_rate_init=0.01, max_iter=500)
mlp.fit(x_data,y_data)

/Users/Yeoni/anaconda/lib/python3.5/site-packages/sklearn/neural_network/multilayer_perceptron.py:563: ConvergenceWarning: Stochastic Optimizer: Maximum iterations reached and the optimization hasn't converged yet.
  % (), ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=4, learning_rate='constant',
       learning_rate_init=0.01, max_iter=500, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='sgd', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [36]:
mlp.predict(x_data)

array([ 0.,  1.,  1.,  0.])

In [47]:
xy = np.loadtxt("xor.txt", unpack=True)

x_data = np.transpose(xy[:-1])
y_data = np.transpose(xy[-1])

mlp = MLPClassifier(hidden_layer_sizes=(10), solver='sgd', learning_rate_init=0.01, max_iter=500)
mlp.fit(x_data,y_data)

prediction = mlp.predict(x_data)

print("총 테스트 개수 :", len(y_data))
print("오류 개수 :", (y_data != prediction).sum())
print("정확도 : ", (y_data == prediction).sum()/len(y_data))

총 테스트 개수 : 4
오류 개수 : 0
정확도 :  1.0


/Users/Yeoni/anaconda/lib/python3.5/site-packages/sklearn/neural_network/multilayer_perceptron.py:563: ConvergenceWarning: Stochastic Optimizer: Maximum iterations reached and the optimization hasn't converged yet.
  % (), ConvergenceWarning)


# MNIST 구현

10층 이상 구현하고 score를 추가함, verbose로 코스트 확인. 